name: Compile Hymnbook with pdfLaTeX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install full TeX Live (includes pdfpages and everything else)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Create output folder
        run: mkdir -p output

      - name: Compile with pdfLaTeX
        run: pdflatex -output-directory=output HymnLatex.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: hymnbook-pdf
          path: output/*.pdf
