name: Compile Amharic Words Only Hymnbook

on:
  # push:
  #   paths:
  #     - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LuaLaTeX and fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-luatex texlive-fonts-recommended fonts-freefont-ttf

      - name: Create output folder
        run: mkdir -p output

      - name: Compile with LuaLaTeX
        run: lualatex -output-directory=output HymnLatex.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: amharic-pdf
          path: output/*.pdf
