name: Build LaTeX with Amharic Support (Minimal Install)

on:
  push:
    paths:
      - '**.tex'
      - 'fonts/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install minimal LaTeX with XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-base texlive-xetex texlive-latex-recommended

      - name: Create output folder
        run: mkdir -p output

      - name: Compile LaTeX file
        run: xelatex -output-directory=output main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: amharic-pdf
          path: output/*.pdf
