name: Build LaTeX with Amharic Support (Minimal Install)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install minimal LaTeX with XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-base texlive-xetex texlive-latex-recommended fontconfig

      - name: Install Noto Sans Ethiopic font
        run: |
          # Create the fonts directory if it doesn't exist
          mkdir -p ~/.fonts
          # Download the Noto Sans Ethiopic font (Regular)
          wget -O ~/.fonts/NotoSansEthiopic-Regular.ttf https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansEthiopic/NotoSansEthiopic-Regular.ttf
          # Update font cache
          fc-cache -fv

      - name: Create output folder
        run: mkdir -p output

      - name: Compile LaTeX file
        run: xelatex -output-directory=output main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: amharic-pdf
          path: output/*.pdf
