name: Compile LaTeX Files

on:
  push:
    paths:
      - 'input/**/*.Tex'
  workflow_dispatch:

jobs:
  compile-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX environment
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base

      - name: Compile LaTeX files
        run: |
          mkdir -p output
          for texfile in input/*.Tex; do
            filename=$(basename "$texfile" .Tex)
            pdflatex -output-directory=output "$texfile"
          done

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: output/*.pdf
