name: Build LilyPond Score

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LilyPond
        run: |
          sudo apt-get update
          sudo apt-get install -y lilypond

      - name: Create output directory
        run: mkdir -p output

      - name: Convert root .ly files to latest version
        run: |
          find . -maxdepth 1 -name "*.ly" -exec convert-ly --from=2.18.2 --to=2.24.2 -e {} \;

      - name: Convert .ly files in Lib/ folder to latest version
        run: |
          find ./Lib -name "*.ly" -exec convert-ly --from=2.18.2 --to=2.24.2 -e {} \;

      - name: Compile only sample.ly
        run: lilypond -o output sample.ly

  #    - name: Auto Commit PDFs
  #       uses: stefanzweifel/git-auto-commit-action@v4
  #      with:
  #        commit_message: "Compiled LaTeX files with View and Print versions"
  #        push_options: '--force'
  #        file_pattern: 'output/*.pdf'
        

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lilypond-pdf
          path: output/sample.pdf
