name: Compile LaTeX with thinLaTeX

on:
  push:
    paths:
      - HymnLatex.tex
      - .github/workflows/compile-latex.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up LaTeX
        uses: dante-ev/latex-action@latest
        with:
          root_file: HymnLatex.tex

      - name: Clone thinLaTeX
        run: |
          git clone https://github.com/thomasWeise/thinLaTeX.git
          mkdir -p ~/.texmf/tex/latex/thinLaTeX
          cp thinLaTeX/thin*.sty ~/.texmf/tex/latex/thinLaTeX/
          texhash ~/.texmf

      - name: Compile LaTeX document
        run: |
          pdflatex HymnLatex.tex
          pdflatex HymnLatex.tex  # Run twice for proper refs

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Compiled-HymnLatex
          path: HymnLatex.pdf
